# Agent 工具配置项

RECURSION_LIMIT: 50

# langgraph 历史记录类型。
# 如果设为 memory, 无法持久化，仅在程序运行期间用于获取历史消息。
# 默认设为 sqlite, 则使用 basic_settings.yaml 中的 SQLITE_GRAPH_DATABASE_URI
# 如果设为 postgres，则使用 basic_settings.yaml 中的 
# POSTGRESQL_GRAPH_DATABASE_URI
# POSTGRESQL_GRAPH_CONNECTION_POOLS_MAX_SIZE
# POSTGRESQL_GRAPH_CONNECTION_POOLS_KWARGS 等配置
# 可选值：['memory', 'sqlite', 'postgres']
GRAPH_MEMORY_TYPE: sqlite
search_internet:
  use: false
  search_engine_name: duckduckgo
  search_engine_config:
    duckduckgo: {}
    tavily:
      tavily_key: ''
    searx:
      host: https://metasearx.com
      engines: []
      categories: []
      language: zh-CN
    bing:
      bing_search_url: https://api.bing.microsoft.com/v7.0/search
      bing_key: ''
    metaphor:
      metaphor_api_key: ''
      split_result: false
      chunk_size: 500
      chunk_overlap: 0
    google:
      google_search_url: https://google.serper.dev/search
      google_key: ''
  top_k: 5
  verbose: Origin
  conclude_prompt: "<指令>这是搜索到的互联网信息，请你根据这些信息进行提取并有调理，简洁的回答问题。如果无法从中得到答案，请说 “无法搜索到能回答问题的内容”。
    </指令>\n<已知信息>{{ context }}</已知信息>\n<问题>\n{{ question }}\n</问题>\n"

# 心知天气（https://www.seniverse.com/）工具配置项
arxiv:
  use: false
weather_check:
  use: false
  api_key: ''
search_youtube:
  use: false

# numexpr 数学计算工具配置项
wolfram:
  use: false
  appid: ''

# 图片生成工具配置项。model 必须是在 model_settings.yaml/MODEL_PLATFORMS 中配置过的。
calculate:
  use: false
text2images:
  use: false
  model: sd-turbo
  size: 256*256

# text2sql使用建议
# 1、因大模型生成的sql可能与预期有偏差，请务必在测试环境中进行充分测试、评估；
# 2、生产环境中，对于查询操作，由于不确定查询效率，推荐数据库采用主从数据库架构，让text2sql连接从数据库，防止可能的慢查询影响主业务；
# 3、对于写操作应保持谨慎，如不需要写操作，设置read_only为True,最好再从数据库层面收回数据库用户的写权限，防止用户通过自然语言对数据库进行修改操作；
# 4、text2sql与大模型在意图理解、sql转换等方面的能力有关，可切换不同大模型进行测试；
# 5、数据库表名、字段名应与其实际作用保持一致、容易理解，且应对数据库表名、字段进行详细的备注说明，帮助大模型更好理解数据库结构；
# 6、若现有数据库表名难于让大模型理解，可配置下面table_comments字段，补充说明某些表的作用。
text2sql:
  model_name: qwen-plus
  use: false
  sqlalchemy_connect_str: mysql+pymysql://用户名:密码@主机地址/数据库名称
  read_only: false
  top_k: 50
  return_intermediate_steps: true
  table_names: []
  table_comments: {}

# 高德地图、天气相关工具配置项。
amap:
  use: false
  api_key: 高德地图 API KEY

# text2promql 使用建议
# 1、因大模型生成的 promql 可能与预期有偏差, 请务必在测试环境中进行充分测试、评估;
# 2、text2promql 与大模型在意图理解、metric 选择、promql 转换等方面的能力有关, 可切换不同大模型进行测试;
# 3、当前仅支持 单prometheus 查询, 后续考虑支持 多prometheus 查询.
text2promql:
  use: false
  prometheus_endpoint: http://127.0.0.1:9090
  username: ''
  password: ''

# URL内容阅读（https://r.jina.ai/）工具配置项
# 请确保部署的网络环境良好，以免造成超时等问题
url_reader:
  use: false
  timeout: 10000
